#!/bin/bash
TARGET="/home/ubuntu/chicode.org-v2"
GIT_DIR="/home/ubuntu/chicode.git"
BRANCH="master"

set -e

while read oldrev newrev ref
do

        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        export MIX_ENV=prod

        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
        cd $TARGET/assets
        npm i --production
        npm run deploy
        cd ../
        mix deps.get
        mix ecto.migrate
        mix phx.digest

        sudo systemctl restart chicode.service
done
